spring:
  datasource:
    url: jdbc:h2:mem:rent-fare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
  sql:
    init:
      platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  application:
    name: rent-fare
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 7001

management:
  endpoints:
    web:
      exposure:
        include: "*"
base:
  currency: "RUB"